image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5000 # preview on browser
  onOpen: open-browser

tasks:
  - init: |
      docker-compose build
    command: |
      docker-compose start
  - command: gp await-port 5000 && gp preview "$(gp url 5000)"
